seq_len: 32
batch_size: 13
n_epoch: 165
learning_rate: 0.01
decay_steps: 10000
decay_rate : 0.1
weight_decay: 0.00004
print_freq: 20
queue_num: 5
start_step: 0

num_classes: 10
dataset_name: skig_rgb_s1
training_datalist: /ssd/gmzhu/SKIG/trte_splits/training_rgb_list1.txt
testing_datalist: /ssd/gmzhu/SKIG/trte_splits/testing_rgb_list1.txt

# modify below if you want to use a custom loader
# data_loader: inputs.prepare_skig_rgb_data
